name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make tests
      run: make run_tests
  windows_install:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: check pwd
      run: pwd
    - name: list items
      run: ls
    - name: install
      run: ./install.bat
    - name: check install
      run: |
        cd ../
        creal.exe ./creal/tests/testmocks/tests.creal
